# Generated by Django 5.2.10 on 2026-03-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_document_remove_patient_notes_patient_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapSystemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Система капп',
                'verbose_name_plural': 'Системы капп',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип лечения',
                'verbose_name_plural': 'Типы лечения',
                'ordering': ['order', 'name'],
            },
        ),
    ]
