# Generated by Django 5.2.10 on 2026-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_capsystemoption_treatmenttypeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatment_stage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Этап лечения'),
        ),
    ]
