# Generated by Django 5.2.10 on 2026-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_treatment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='parent_report_read',
            field=models.BooleanField(default=False, verbose_name='Отчёт по визиту прочитан родителем'),
        ),
        migrations.AddField(
            model_name='visit',
            name='parent_visit_read',
            field=models.BooleanField(default=False, verbose_name='Уведомление о визите прочитано родителем'),
        ),
    ]
