name: rabotniki
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_inappwebview_platform_interface: ^1.3.0+1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true