# Generated by Django 5.2.10 on 2026-02-11 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_visit_parent_report_read_visit_parent_visit_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='QR активирован')),
                ('coin_balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Баланс не может быть отрицательным')], verbose_name='Баланс игрока')),
                ('xp_balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Опыт не может быть отрицательным')], verbose_name='Опыт игрока')),
                ('play_day', models.IntegerField(default=1, verbose_name='Дней в игре')),
                ('aligner', models.BooleanField(default=False, verbose_name='Элайнер')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Аватар пациента',
                'verbose_name_plural': 'Аватары пациентов',
                'constraints': [models.CheckConstraint(condition=models.Q(('coin_balance__gte', 0)), name='coin_balance_not_negative'), models.CheckConstraint(condition=models.Q(('xp_balance__gte', 0)), name='xp_balance_not_negative')],
            },
        ),
    ]
