# Generated by Django 5.2.10 on 2026-02-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('patients', '0006_visit_parent_report_read_visit_parent_visit_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название видео')),
                ('preview', models.ImageField(upload_to='videos/previews/', verbose_name='Превью видео')),
                ('video', models.FileField(upload_to='videos/files/', verbose_name='Видео')),
                ('coin_reward', models.PositiveIntegerField(default=10, verbose_name='Награда(монеты)')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name='Награда(опыт)')),
                ('status', models.BooleanField(default=False, verbose_name='Активно')),
                ('unlock_day', models.PositiveIntegerField(default=1, help_text='День, в который открывается видео', verbose_name='День открытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео-урок',
                'verbose_name_plural': 'Библиотека видео',
            },
        ),
        migrations.CreateModel(
            name='PatientVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус просмотра')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name='Дата просмотра')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='patients.patient')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='game.videoitem')),
            ],
            options={
                'verbose_name': 'Прогресс видео',
                'verbose_name_plural': 'Прогресс видео',
                'unique_together': {('patient', 'video')},
            },
        ),
    ]
