# Generated by Django 5.2.10 on 2026-02-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_videoitem_patientvideo'),
        ('patients', '0006_visit_parent_report_read_visit_parent_visit_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('coin_reward', models.PositiveIntegerField(default=10, verbose_name='Награда(монеты)')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name='Награда(опыт)')),
                ('status', models.BooleanField(default=False, verbose_name='Активно')),
                ('unlock_day', models.PositiveIntegerField(default=1, help_text='День, в который открывается задание', verbose_name='День открытия')),
                ('patient_type', models.CharField(choices=[('child', 'ребенок'), ('teen', 'подросток')], default='kid', verbose_name='Тип пациента')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Список заданий',
            },
        ),
        migrations.CreateModel(
            name='PatientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='patients.patient')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='game.taskitem')),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогресс заданий',
                'unique_together': {('patient', 'task')},
            },
        ),
    ]
