# Generated by Django 5.2.10 on 2026-02-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_taskitem_patienttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('preview', models.ImageField(upload_to='reward/previews/', verbose_name='Картинка предмета')),
                ('coin_cost', models.PositiveIntegerField(verbose_name='Цена в монетах')),
                ('xp_cost', models.PositiveIntegerField(verbose_name='Цена в опыте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно к покупке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет магазина',
                'verbose_name_plural': 'Магазин предметов',
            },
        ),
        migrations.CreateModel(
            name='SettingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название настройки')),
                ('slug', models.SlugField(unique=True, verbose_name='Код для фронта')),
            ],
            options={
                'verbose_name': 'Справочник настроек',
                'verbose_name_plural': 'Справочник настроек',
            },
        ),
        migrations.AlterUniqueTogether(
            name='patientvideo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patientvideo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvideo',
            name='video',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='patient_type',
            field=models.CharField(choices=[('child', 'ребенок'), ('teen', 'подросток')], default='child', verbose_name='Тип пациента'),
        ),
        migrations.CreateModel(
            name='AvatarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='game.catavatar')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.taskitem')),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогресс заданий',
                'unique_together': {('avatar', 'task')},
            },
        ),
        migrations.CreateModel(
            name='AvatarVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус просмотра')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name='Дата просмотра')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='game.catavatar')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.videoitem')),
            ],
            options={
                'verbose_name': 'Прогресс видео',
                'verbose_name_plural': 'Прогресс видео',
                'unique_together': {('avatar', 'video')},
            },
        ),
        migrations.CreateModel(
            name='AvatarReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Надето')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.catavatar')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rewarditem')),
            ],
            options={
                'verbose_name': 'Инвентарь пациента',
                'verbose_name_plural': 'Инвентарь пациентов',
                'unique_together': {('avatar', 'reward')},
            },
        ),
        migrations.CreateModel(
            name='AvatarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Переключатель настройки')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='game.catavatar')),
                ('setting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.settingitem')),
            ],
            options={
                'verbose_name': 'Настройка аватара',
                'verbose_name_plural': 'Настройки аватаров',
                'unique_together': {('avatar', 'setting_item')},
            },
        ),
        migrations.DeleteModel(
            name='PatientTask',
        ),
        migrations.DeleteModel(
            name='PatientVideo',
        ),
    ]
