# Generated by Django 5.2.10 on 2026-03-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rewarditem_settingitem_and_more'),
        ('game', '0005_avatarsosalert'),
    ]

    operations = [
    ]
