# Generated by Django 5.2.10 on 2026-04-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично')], default='success', max_length=20)),
                ('fcm_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Лог уведомлений',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID владельца')),
                ('token', models.TextField(unique=True, verbose_name='FCM токен')),
                ('device_id', models.CharField(blank=True, max_length=255, verbose_name='ID устройства')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('apple', 'iOS (Apple)'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Тип устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип владельца')),
            ],
            options={
                'verbose_name': 'FCM токен',
                'verbose_name_plural': 'FCM токены',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificatio_content_279cf0_idx'), models.Index(fields=['token'], name='notificatio_token_23c95b_idx')],
            },
        ),
    ]
